name: Go Integration Test
description: >-
  instruments and collects coverage from a golang application using
  https://go.dev/testing/coverage/
author: William Artero
branding:
  icon: box
  color: blue
inputs:
  cover-dir:
    description: directory that for the instrumentation coverage result
    required: false
  run-flags:
    description: extra build/run flags to pass to go run
    required: false
  cover-profile:
    description: cover profile file path/name
    required: false
  coverage-packages:
    description: package names to include in the report
    required: false
  packages:
    description: package names to be built
    required: false
  report-file:
    description: JSON report file path/name
    required: false
outputs:
  cover-profile:
    description: cover profile file path/name
    value: ${{ steps.run.outputs.cover-profile }}
  report-file:
    description: JSON report file path/name
    value: ${{ steps.run.outputs.report-file }}
runs:
  using: composite
  steps:
  - id: run
    run: ${{ github.action_path }}/action.bash
    shell: bash
    env:
      GOCOVERDIR: ${{ inputs.cover-dir }}
      GOLANG_COVERAGE_PACKAGES: ${{ inputs.coverage-packages }}
      GOLANG_COVERPROFILE: ${{ inputs.cover-profile }}
      GOLANG_PACKAGES: ${{ inputs.packages }}
      GOLANG_REPORTFILE: ${{ inputs.report-file }}
      GOLANG_RUN_FLAGS: ${{ inputs.run-flags }}
